version: "3.7"
services:
  bootstrap:
    image: nuts-network:latest
    environment:
      NUTS_ADDRESS: 0.0.0.0:1323
      NUTS_IDENTITY: urn:oid:1.3.6.1.4.1.54851.4:00000001
      NUTS_CERTFILE: /etc/nuts/certificate-and-key.pem
      NUTS_CERTKEYFILE: /etc/nuts/certificate-and-key.pem
#      NUTS_DEBUG_LOCKS: "true"
#      GRPC_GO_LOG_SEVERITY_LEVEL: info
#      GRPC_GO_LOG_VERBOSITY_LEVEL: 2
    command: ["/bin/sh", "-c", "/usr/bin/nuts-network server --publicAddr=bootstrap:5555 --nodeID=bootstrap"]
    networks:
      - nuts
    volumes:
      - ./test-files/certificate-and-key.pem:/etc/nuts/certificate-and-key.pem:ro
      - ./test-files/truststore.pem:/etc/nuts/truststore.pem:ro
    ports:
      - "1323:1323"
  node:
    image: nuts-network:latest
    environment:
      NUTS_IDENTITY: urn:oid:1.3.6.1.4.1.54851.4:00000001
      NUTS_BOOTSTRAPNODES: bootstrap:5555
      NUTS_CERTFILE: /etc/nuts/certificate-and-key.pem
      NUTS_CERTKEYFILE: /etc/nuts/certificate-and-key.pem
#      GRPC_GO_LOG_SEVERITY_LEVEL: info
#      GRPC_GO_LOG_VERBOSITY_LEVEL: 2
    networks:
      - nuts
    volumes:
      - ./test-files/certificate-and-key.pem:/etc/nuts/certificate-and-key.pem:ro
      - ./test-files/truststore.pem:/etc/nuts/truststore.pem:ro

networks:
  nuts:
    name: nuts
