version: "3.7"
services:
  bootstrap:
    image: nuts-network:latest
    environment:
      NUTS_ADDRESS: 0.0.0.0:1323
      NUTS_IDENTITY: urn:oid:1.3.6.1.4.1.54851.4:00000001
      NUTS_NODEID: bootstrap
      NUTS_PUBLICADDR: bootstrap:5555
    command: ["/bin/sh", "-c", "/usr/bin/nuts-network server --publicAddr=bootstrap:5555 --nodeId=bootstrap"]
    networks:
      - nuts
    ports:
      - "1323:1323"
  node:
    image: nuts-network:latest
    environment:
      NUTS_IDENTITY: urn:oid:1.3.6.1.4.1.54851.4:00000001
      NUTS_BOOTSTRAPNODES: bootstrap:5555
    networks:
      - nuts
networks:
  nuts:
    name: nuts
